/**
 * WSPersonService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.ibm.itim.ws.services;

public interface WSPersonService extends java.rmi.Remote {
    public com.ibm.itim.ws.model.WSRequest addRole(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.lang.String roleDN, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest addRolesToPerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.lang.String[] roleDNs, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest createPerson(com.ibm.itim.ws.model.WSSession session, com.ibm.itim.ws.model.WSOrganizationalContainer wsContainer, com.ibm.itim.ws.model.WSPerson wsPerson, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest deletePerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSAccount[] getAccountsByOwner(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public java.lang.String[] getAuthorizedPersonProfilesForCreate(com.ibm.itim.ws.model.WSSession session, com.ibm.itim.ws.model.WSOrganizationalContainer wsContainer) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSService[] getAuthorizedServices(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSAccount[] getFilteredAccountsByOwner(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, com.ibm.itim.ws.model.WSAttribute filterAttribute) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSService[] getFilteredAuthorizedServices(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, com.ibm.itim.ws.model.WSAttribute filterAttribute) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRole[] getPersonRoles(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSPerson getPrincipalPerson(com.ibm.itim.ws.model.WSSession session) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSInvalidSessionException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public boolean isCreatePersonAllowed(com.ibm.itim.ws.model.WSSession session) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException, com.ibm.itim.ws.exceptions.WSUnsupportedVersionException;
    public boolean isMemberOfRole(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.lang.String roleDN) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSPerson lookupPerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSInvalidSessionException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest modifyPerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, com.ibm.itim.ws.model.WSAttribute[] wsAttrs, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest removeRole(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.lang.String roleDN, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest removeRolesFromPerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.lang.String[] roleDNs, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest restorePerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, boolean restoreAccounts, java.lang.String password, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSInvalidSessionException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSPerson[] searchPersonsFromRoot(com.ibm.itim.ws.model.WSSession session, java.lang.String filter, java.lang.String[] attrList) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSPerson[] searchPersonsWithITIMAccount(com.ibm.itim.ws.model.WSSession session, java.lang.String filter, java.lang.String[] attrList) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public void selfRegister(com.ibm.itim.ws.model.WSPerson wsPerson, java.lang.String tenantId) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest suspendPerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest suspendPersonAdvanced(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, boolean includeAccounts, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest synchGeneratedPassword(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest synchPasswords(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, java.lang.String password, java.util.Calendar date, boolean notifyByMail) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
    public com.ibm.itim.ws.model.WSRequest transferPerson(com.ibm.itim.ws.model.WSSession session, java.lang.String personDN, com.ibm.itim.ws.model.WSOrganizationalContainer targetContainer, java.util.Calendar date) throws java.rmi.RemoteException, com.ibm.itim.ws.exceptions.WSLoginServiceException, com.ibm.itim.ws.exceptions.WSApplicationException;
}
